# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    tags:
      - '**'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Build
      run: go build -ldflags "-w -s"

    - name: GH Release
      uses: softprops/action-gh-release@v2.2.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sasayaki
