# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
    push:
        tags:
            - '**'

jobs:
    release-windows:
        runs-on: windows-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up CMake
              uses: lukka/get-cmake@latest

            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v2

            - name: Build whisper.cpp
              run: |
                  git clone https://github.com/ggerganov/whisper.cpp.git
                  cd whisper.cpp
                  cmake -B build -DBUILD_SHARED_LIBS=OFF
                  cmake --build build --config Release 
                  cd ..
                  .\whisper.cpp\build\bin\Release\whisper-cli.exe --help
                  copy .\whisper.cpp\build\bin\Release\whisper-cli.exe embed

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 'stable'

            - name: Build
              run: |
                  go mod tidy
                  go build -ldflags "-w -s" -o "sasayaki-windows.exe"
                  .\sasayaki-windows.exe --cpp

            - name: GH Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body_path: .github/release-notes.md
                  files: sasayaki-windows.exe

    release-linux:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Build whisper.cpp
              run: |
                  sudo apt update
                  sudo apt install -y build-essential cmake
                  git clone https://github.com/ggerganov/whisper.cpp.git
                  cd whisper.cpp
                  cmake -B build -DBUILD_SHARED_LIBS=OFF
                  cmake --build build --config Release
                  cd ..
                  whisper.cpp/build/bin/whisper-cli --help
                  cp whisper.cpp/build/bin/whisper-cli embed

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 'stable'

            - name: Build
              run: |
                  go mod tidy
                  go build -ldflags "-w -s" -o "sasayaki-linux"
                  ./sasayaki-linux

            - name: GH Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body_path: .github/release-notes.md
                  files: sasayaki-linux

    release-macos:
        runs-on: macos-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Build whisper.cpp
              run: |
                  brew update
                  brew install cmake
                  git clone https://github.com/ggerganov/whisper.cpp.git
                  cd whisper.cpp
                  cmake -B build -DBUILD_SHARED_LIBS=OFF
                  cmake --build build --config Release 
                  cd ..
                  whisper.cpp/build/bin/whisper-cli --help
                  cp whisper.cpp/build/bin/whisper-cli embed

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 'stable'

            - name: Build
              run: |
                  go mod tidy
                  go build -ldflags "-w -s" -o "sasayaki-macos"
                  ./sasayaki-macos

            - name: GH Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body_path: .github/release-notes.md
                  files: sasayaki-macos
